# This file was generated by GoReleaser. DO NOT EDIT.
cask "hello-world" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/jericop/hello-world-go-app/releases/download/v#{version}/hello-world-go-app_Darwin_x86_64.tar.gz"
      sha256 "161a1ca8346537345a6b18d2598a93ca07fe70fd684a623d711a1f7c7b1a3555"
    end
    on_arm do
      url "https://github.com/jericop/hello-world-go-app/releases/download/v#{version}/hello-world-go-app_Darwin_arm64.tar.gz"
      sha256 "b252a3a9d3cf1b132f76984d6b048d16619a6cc4b703bc85eae3f79f6c15ce2f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jericop/hello-world-go-app/releases/download/v#{version}/hello-world-go-app_Linux_x86_64.tar.gz"
      sha256 "1cc9fd5397b3e917310561ec96c6e3a0700ce62c68bc8d09bdecb4ba4140c086"
    end
    on_arm do
      url "https://github.com/jericop/hello-world-go-app/releases/download/v#{version}/hello-world-go-app_Linux_arm64.tar.gz"
      sha256 "56b25351f097a9e165711bb797bad995af0e187a2fe0eaa41e755aa52c739d6b"
    end
  end

  name "hello-world"
  desc "A simple Go command-line tool that prints hello world"
  homepage "https://github.com/jericop/hello-world-go-app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hello-world"

  # No zap stanza required

end
