# This file was generated by GoReleaser. DO NOT EDIT.
cask "hello-world" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/jericop/hello-world-go-app/releases/download/v#{version}/hello-world-go-app_Darwin_x86_64.tar.gz"
      sha256 "a122b8952c0f61f77b8d2bb9c84731579184c59dcd4ab408ce4f5f5d0c0eada0"
    end
    on_arm do
      url "https://github.com/jericop/hello-world-go-app/releases/download/v#{version}/hello-world-go-app_Darwin_arm64.tar.gz"
      sha256 "c8858e8a8e34592b239134153b607548f56c155a40c44e54ae6c81bcc7185c03"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jericop/hello-world-go-app/releases/download/v#{version}/hello-world-go-app_Linux_x86_64.tar.gz"
      sha256 "cf2429dade1de93cccae9f9b746797dd5003fddd57b0de3333881c34e7f5f3bf"
    end
    on_arm do
      url "https://github.com/jericop/hello-world-go-app/releases/download/v#{version}/hello-world-go-app_Linux_arm64.tar.gz"
      sha256 "3734f03c0970c2a635dac86c0591b218c4a2c499b04782bf8c5dea6d9eeb01d1"
    end
  end

  name "hello-world"
  desc "A simple Go command-line tool that prints hello world"
  homepage "https://github.com/jericop/hello-world-go-app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hello-world"

  # No zap stanza required

end
